# Generated by Django 5.0.3 on 2026-05-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.CharField(help_text="e.g., 'mercedes'", max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_avg_speed_kmh', models.FloatField()),
                ('power_hp', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('image_path', models.CharField(help_text="e.g., 'img/mercedes-amg.png'", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.CharField(help_text="e.g., 'monza'", max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('length_km', models.FloatField()),
                ('speed_multiplier', models.FloatField()),
                ('image_path', models.CharField(help_text="e.g., 'img/monza.png'", max_length=255)),
            ],
        ),
    ]
